baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Multi-scales forest dynamics models"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Aitor Ameztegui"
  bio = ""
  job = "Lecturer/Researcher"
  location = "University of Lleida"
  gravatarEmail = "aitor.ameztegui@eagrof.udl.cat"
  # Your profile picture
#  picture = ""
  twitter = "multivac42"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 4
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"
[[menu.main]]
  weight = 5
  identifier = "github"
  name = "GitHub"
  pre = "<i class='fab fa-github fa-lg'></i>"
  url = "https://github.com/ameztegui/"
[[menu.main]]
  weight = 3
  identifier = "models"
  name = "Models"
  pre = "<i class='fa fa-code-fork fa-lg'></i>"
  url = "/models"


[[menu.footer]]
  weight = 1
  identifier = "Lleida"
  name = "University of Lleida"
  pre = "<i class='fa fa-university fa-lg'></i>"
  url = "http://udl.cat/"
[[menu.footer]]
  weight = 2
  name = "RStudio"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://rstudio.cloud/"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/Sta199-S18/"
[[menu.footer]]


[params]
  dateFormat = "January 2, 2006"
  background = "http://www2.stat.duke.edu/courses/Spring18/Sta199/img/mugesketch.png"
  favicon = "img/favicon.ico"
